[default]
SECRET_KEY = "you-will-never-guess"
DB_USERNAME = "app_user"
DB_PASSWORD = "app_password"
DATABASE_NAME = "app"
DATABASE_SQLITE = true
CORS_ORIGINS = "*"
DESCOPE_PROJECT_ID=""
DESCOPE_PROJECT_KEY=""
RABBITMQ_ENABLED = false
RABBITMQ_HOST = 'localhost'
RABBITMQ_USERNAME = 'guest'
RABBITMQ_PASSWORD = 'guest'
REDIS_URL = "redis://localhost:6379/0"

[development]
DB_HOST = "localhost"
SQLALCHEMY_DATABASE_URI = "@jinja postgresql://{{ this.DB_USERNAME }}:{{ this.DB_PASSWORD }}@{{ this.DB_HOST }}:5432/{{ this.DATABASE_NAME }}"
REDIS_URL = "redis://localhost:6379/0"

[docker]
RABBITMQ_ENABLED = true
DB_HOST = "db" 
SQLALCHEMY_DATABASE_URI = "@jinja postgresql://{{ this.DB_USERNAME }}:{{ this.DB_PASSWORD }}@{{ this.DB_HOST }}:5432/{{ this.DATABASE_NAME }}"
REDIS_URL = "redis://localhost:6379/0"

[devcontainer]
RABBITMQ_ENABLED = true
DB_HOST = "db" 
SQLALCHEMY_DATABASE_URI = "@jinja postgresql://{{ this.DB_USERNAME }}:{{ this.DB_PASSWORD }}@{{ this.DB_HOST }}:5432/{{ this.DATABASE_NAME }}"
REDIS_URL = "redis://localhost:6379/0"

[testing_devcontainer]
RABBITMQ_ENABLED = true
TESTING = true
DB_HOST = "db" 
DATABASE_TEST_NAME = "test_app"
SQLALCHEMY_DATABASE_URI = "@jinja postgresql://{{ this.DB_USERNAME }}:{{ this.DB_PASSWORD }}@{{ this.DB_HOST }}:5432/{{ this.DATABASE_TEST_NAME }}"
REDIS_URL = "redis://localhost:6379/0"

[testing_gha]
TESTING = true
DB_HOST = "localhost" 
DATABASE_TEST_NAME = "test_app"
SQLALCHEMY_DATABASE_URI = "@jinja postgresql://{{ this.DB_USERNAME }}:{{ this.DB_PASSWORD }}@{{ this.DB_HOST }}:5432/{{ this.DATABASE_TEST_NAME }}"
REDIS_URL = "redis://localhost:6379/0"

[staging]
RABBITMQ_ENABLED = true
DB_HOST = "localhost" 
DATABASE_TEST_NAME = "test_app"
SQLALCHEMY_DATABASE_URI = "@jinja postgresql://{{ this.DB_USERNAME }}:{{ this.DB_PASSWORD }}@{{ this.DB_HOST }}:5432/{{ this.DATABASE_TEST_NAME }}"
REDIS_URL = "redis://localhost:6379/0"

[production]
RABBITMQ_ENABLED = true
DB_HOST = "localhost" 
DATABASE_TEST_NAME = "test_app"
SQLALCHEMY_DATABASE_URI = "@jinja postgresql://{{ this.DB_USERNAME }}:{{ this.DB_PASSWORD }}@{{ this.DB_HOST }}:5432/{{ this.DATABASE_TEST_NAME }}"
REDIS_URL = "redis://localhost:6379/0"