version: '2'
services:
  web:
    image: server
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached    
    depends_on:
      - db
      - rabbitmq
      - redis
      - elasticsearch
    ports:
      - "5000:5000"  
    environment:
      ENV_FOR_DYNACONF: devcontainer
    command: /bin/sh -c "while sleep 1000; do :; done"
  db:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: app
    ports:
      - 5432:5432
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 20s
      retries: 5
  redis:
    image: redis:7
    restart: always
    ports:
      - ${REDIS_PORT}:6379
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    environment:
      - node.name=es-node
      - cluster.name=es-cluster
      - discovery.type=single-node
    networks:
      - gateway_network
    volumes:
      - local_es:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"